from __future__ import annotations

import json

from common import q
from private_runtime_lib.common import split_host_port


def nft_dropin_command() -> str:
    return (
        "set -e; "
        "sudo mkdir -p /etc/nftables.d; "
        "sudo touch /etc/nftables.conf; "
        "if ! grep -q '/etc/nftables.d/\\*.nft' /etc/nftables.conf; then "
        "printf '\\ninclude \"/etc/nftables.d/*.nft\"\\n' | sudo tee -a /etc/nftables.conf >/dev/null; "
        "fi; "
        "test -d /etc/nftables.d; "
        "grep -q '/etc/nftables.d/\\*.nft' /etc/nftables.conf"
    )

def dns_probe_python(
    names: list[str],
    upstream_host: str,
    upstream_port: str,
    timeout: int,
) -> str:
    names_json = json.dumps(names)
    return (
        "DYNET_RUNTIME_DNS_NAMES="
        + q(names_json)
        + " python3 - <<'PY_DYNET_PRIVATE_DNS'\n"
        "import json\n"
        "import os\n"
        "import random\n"
        "import socket\n"
        f"upstream = ({upstream_host!r}, {int(upstream_port)!r})\n"
        f"timeout = {int(timeout)!r}\n"
        "names = json.loads(os.environ['DYNET_RUNTIME_DNS_NAMES'])\n"
        "for name in names:\n"
        "    query_id = random.randrange(0, 65536)\n"
        "    packet = bytearray(query_id.to_bytes(2, 'big'))\n"
        "    packet.extend(b'\\x01\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00')\n"
        "    for label in name.split('.'):\n"
        "        encoded = label.encode('ascii')\n"
        "        packet.append(len(encoded))\n"
        "        packet.extend(encoded)\n"
        "    packet.extend(b'\\x00\\x00\\x01\\x00\\x01')\n"
        "    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)\n"
        "    sock.settimeout(timeout)\n"
        "    sock.sendto(bytes(packet), upstream)\n"
        "    try:\n"
        "        data, _ = sock.recvfrom(4096)\n"
        "    except TimeoutError:\n"
        "        print('[runtime-private] dns %s timeout' % name)\n"
        "        continue\n"
        "    if len(data) < 12 or data[:2] != query_id.to_bytes(2, 'big'):\n"
        "        print('[runtime-private] dns %s invalid-response' % name)\n"
        "        continue\n"
        "    print('[runtime-private] dns %s bytes=%d' % (name, len(data)))\n"
        "PY_DYNET_PRIVATE_DNS\n"
    )

def tcp_probe_python(
    names: list[str],
    upstream_host: str,
    upstream_port: str,
    timeout: int,
    output_path: str,
) -> str:
    names_json = json.dumps(names)
    return (
        "DYNET_RUNTIME_TCP_NAMES="
        + q(names_json)
        + " DYNET_RUNTIME_TCP_OUT="
        + q(output_path)
        + " python3 - <<'PY_DYNET_PRIVATE_TCP'\n"
        "import json\n"
        "import os\n"
        "import random\n"
        "import socket\n"
        "import ssl\n"
        "import subprocess\n"
        "import time\n"
        f"upstream = ({upstream_host!r}, {int(upstream_port)!r})\n"
        f"timeout = {int(timeout)!r}\n"
        "names = json.loads(os.environ['DYNET_RUNTIME_TCP_NAMES'])\n"
        "out = os.environ['DYNET_RUNTIME_TCP_OUT']\n"
        "routes = []\n"
        "def read_name(data, offset):\n"
        "    labels = []\n"
        "    jumped = False\n"
        "    end = offset\n"
        "    seen = 0\n"
        "    while True:\n"
        "        if offset >= len(data):\n"
        "            raise ValueError('dns name exceeds packet')\n"
        "        length = data[offset]\n"
        "        if length & 0xc0 == 0xc0:\n"
        "            if offset + 1 >= len(data):\n"
        "                raise ValueError('dns pointer exceeds packet')\n"
        "            if not jumped:\n"
        "                end = offset + 2\n"
        "            offset = ((length & 0x3f) << 8) | data[offset + 1]\n"
        "            jumped = True\n"
        "            seen += 1\n"
        "            if seen > 16:\n"
        "                raise ValueError('dns pointer loop')\n"
        "            continue\n"
        "        offset += 1\n"
        "        if length == 0:\n"
        "            return '.'.join(labels), (end if jumped else offset)\n"
        "        label = data[offset:offset + length].decode('ascii', 'ignore')\n"
        "        labels.append(label.lower())\n"
        "        offset += length\n"
        "def dns_query(name):\n"
        "    query_id = random.randrange(0, 65536)\n"
        "    packet = bytearray(query_id.to_bytes(2, 'big'))\n"
        "    packet.extend(b'\\x01\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00')\n"
        "    for label in name.split('.'):\n"
        "        encoded = label.encode('ascii')\n"
        "        packet.append(len(encoded))\n"
        "        packet.extend(encoded)\n"
        "    packet.extend(b'\\x00\\x00\\x01\\x00\\x01')\n"
        "    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)\n"
        "    sock.settimeout(timeout)\n"
        "    started = time.monotonic()\n"
        "    sock.sendto(bytes(packet), upstream)\n"
        "    data, _ = sock.recvfrom(4096)\n"
        "    elapsed_ms = int((time.monotonic() - started) * 1000)\n"
        "    if len(data) < 12 or data[:2] != query_id.to_bytes(2, 'big'):\n"
        "        raise ValueError('invalid dns response')\n"
        "    qd = int.from_bytes(data[4:6], 'big')\n"
        "    an = int.from_bytes(data[6:8], 'big')\n"
        "    offset = 12\n"
        "    for _ in range(qd):\n"
        "        _, offset = read_name(data, offset)\n"
        "        offset += 4\n"
        "    addresses = []\n"
        "    for _ in range(an):\n"
        "        _, offset = read_name(data, offset)\n"
        "        rtype = int.from_bytes(data[offset:offset+2], 'big')\n"
        "        ttl = int.from_bytes(data[offset+4:offset+8], 'big')\n"
        "        rdlen = int.from_bytes(data[offset+8:offset+10], 'big')\n"
        "        offset += 10\n"
        "        rdata = data[offset:offset+rdlen]\n"
        "        offset += rdlen\n"
        "        if rtype == 1 and rdlen == 4:\n"
        "            addresses.append({'ip': '.'.join(str(b) for b in rdata), 'ttl': ttl})\n"
        "    return {'bytes': len(data), 'elapsedMs': elapsed_ms, 'addresses': addresses}\n"
        "def route_ip(ip):\n"
        "    subprocess.run(['sudo', 'ip', 'route', 'replace', ip + '/32', 'dev', 'dynet0'], check=True)\n"
        "    routes.append(ip)\n"
        "def https_head(name, ip):\n"
        "    context = ssl.create_default_context()\n"
        "    started = time.monotonic()\n"
        "    raw = socket.create_connection((ip, 443), timeout=timeout)\n"
        "    with context.wrap_socket(raw, server_hostname=name) as tls:\n"
        "        tls.settimeout(timeout)\n"
        "        request = ('HEAD / HTTP/1.1\\r\\nHost: %s\\r\\nUser-Agent: dynet-private-runtime-probe/1\\r\\nConnection: close\\r\\n\\r\\n' % name).encode('ascii')\n"
        "        tls.sendall(request)\n"
        "        data = tls.recv(4096)\n"
        "    elapsed_ms = int((time.monotonic() - started) * 1000)\n"
        "    line = data.splitlines()[0].decode('iso-8859-1', 'replace') if data else ''\n"
        "    return {'elapsedMs': elapsed_ms, 'bytes': len(data), 'statusLine': line, 'ok': line.startswith('HTTP/')}\n"
        "results = []\n"
        "try:\n"
        "    for name in names:\n"
        "        item = {'name': name}\n"
        "        try:\n"
        "            dns = dns_query(name)\n"
        "            item['dns'] = dns\n"
        "            ip = dns['addresses'][0]['ip'] if dns['addresses'] else ''\n"
        "            item['ip'] = ip\n"
        "            if not ip:\n"
        "                raise RuntimeError('no A record')\n"
        "            route_ip(ip)\n"
        "            item['https'] = https_head(name, ip)\n"
        "        except Exception as exc:\n"
        "            item['error'] = str(exc)\n"
        "        results.append(item)\n"
        "finally:\n"
        "    for ip in routes:\n"
        "        subprocess.run(['sudo', 'ip', 'route', 'del', ip + '/32', 'dev', 'dynet0'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n"
        "    with open(out, 'w') as fh:\n"
        "        json.dump({'schema': 'dynet-vm-private-runtime-tcp-probe/v1alpha1', 'results': results}, fh, sort_keys=True)\n"
        "    for item in results:\n"
        "        print('[runtime-private] tcp %s ok=%s error=%s' % (item.get('name'), item.get('https', {}).get('ok'), item.get('error', '')))\n"
        "PY_DYNET_PRIVATE_TCP\n"
    )

def udp_probe_python(target: str, timeout: int, output_path: str) -> str:
    host, port = split_host_port(target)
    return (
        "DYNET_RUNTIME_UDP_OUT="
        + q(output_path)
        + " python3 - <<'PY_DYNET_PRIVATE_UDP'\n"
        "import json\n"
        "import os\n"
        "import socket\n"
        "import subprocess\n"
        "import time\n"
        f"target = ({host!r}, {int(port)!r})\n"
        f"timeout = {int(timeout)!r}\n"
        "out = os.environ['DYNET_RUNTIME_UDP_OUT']\n"
        "packet = b'\\x1b' + (b'\\x00' * 47)\n"
        "result = {'schema': 'dynet-vm-private-runtime-udp-probe/v1alpha1', 'target': '%s:%s' % target}\n"
        "try:\n"
        "    subprocess.run(['sudo', 'ip', 'route', 'replace', target[0] + '/32', 'dev', 'dynet0'], check=True)\n"
        "    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)\n"
        "    sock.settimeout(timeout)\n"
        "    started = time.monotonic()\n"
        "    sent = sock.sendto(packet, target)\n"
        "    data, _ = sock.recvfrom(512)\n"
        "    result.update({'ok': len(data) >= 48, 'sentBytes': sent, 'receivedBytes': len(data), 'elapsedMs': int((time.monotonic() - started) * 1000)})\n"
        "except Exception as exc:\n"
        "    result.update({'ok': False, 'error': str(exc)})\n"
        "finally:\n"
        "    subprocess.run(['sudo', 'ip', 'route', 'del', target[0] + '/32', 'dev', 'dynet0'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n"
        "    with open(out, 'w') as fh:\n"
        "        json.dump(result, fh, sort_keys=True)\n"
        "    print('[runtime-private] udp target=%s:%s ok=%s error=%s' % (target[0], target[1], result.get('ok'), result.get('error', '')))\n"
        "PY_DYNET_PRIVATE_UDP\n"
    )

def ipv6_leak_probe_python(target: str, timeout: int, output_path: str) -> str:
    host, port = split_host_port(target)
    return (
        "DYNET_RUNTIME_IPV6_OUT="
        + q(output_path)
        + " python3 - <<'PY_DYNET_PRIVATE_IPV6'\n"
        "import json\n"
        "import os\n"
        "import socket\n"
        "import subprocess\n"
        "import time\n"
        f"target = ({host!r}, {int(port)!r})\n"
        f"timeout = {int(timeout)!r}\n"
        "out = os.environ['DYNET_RUNTIME_IPV6_OUT']\n"
        "result = {'schema': 'dynet-vm-private-runtime-ipv6-no-leak/v1alpha1', 'target': '[%s]:%s' % target}\n"
        "try:\n"
        "    subprocess.run(['sudo', 'ip', '-6', 'addr', 'replace', 'fd00:6177::1/64', 'dev', 'dynet0'], check=True)\n"
        "    subprocess.run(['sudo', 'ip', '-6', 'route', 'replace', target[0] + '/128', 'dev', 'dynet0'], check=True)\n"
        "    sock = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM)\n"
        "    sock.settimeout(timeout)\n"
        "    started = time.monotonic()\n"
        "    sent = sock.sendto(b'dynet-ipv6-no-leak', target)\n"
        "    try:\n"
        "        data, _ = sock.recvfrom(512)\n"
        "        result.update({'ok': False, 'sentBytes': sent, 'receivedBytes': len(data), 'elapsedMs': int((time.monotonic() - started) * 1000), 'error': 'unexpected IPv6 response'})\n"
        "    except TimeoutError:\n"
        "        result.update({'ok': True, 'sentBytes': sent, 'receivedBytes': 0, 'elapsedMs': int((time.monotonic() - started) * 1000), 'closed': 'timeout-no-response'})\n"
        "except Exception as exc:\n"
        "    result.update({'ok': False, 'error': str(exc)})\n"
        "finally:\n"
        "    subprocess.run(['sudo', 'ip', '-6', 'route', 'del', target[0] + '/128', 'dev', 'dynet0'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n"
        "    subprocess.run(['sudo', 'ip', '-6', 'addr', 'del', 'fd00:6177::1/64', 'dev', 'dynet0'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n"
        "    with open(out, 'w') as fh:\n"
        "        json.dump(result, fh, sort_keys=True)\n"
        "    print('[runtime-private] ipv6 target=%s:%s ok=%s error=%s' % (target[0], target[1], result.get('ok'), result.get('error', '')))\n"
        "PY_DYNET_PRIVATE_IPV6\n"
    )
