from __future__ import annotations

from common import q
from private_runtime_lib.common import WORKLOAD_PROBE_SCHEMA


def workload_probe_python(
    manifest_path: str,
    upstream_host: str,
    upstream_port: str,
    timeout: int,
    output_path: str,
    respect_schedule: bool,
) -> str:
    return (
        "DYNET_RUNTIME_WORKLOAD_MANIFEST="
        + q(manifest_path)
        + " DYNET_RUNTIME_WORKLOAD_OUT="
        + q(output_path)
        + " python3 - <<'PY_DYNET_PRIVATE_WORKLOAD'\n"
        "import json\n"
        "import os\n"
        "import random\n"
        "import socket\n"
        "import ssl\n"
        "import subprocess\n"
        "import time\n"
        "from collections import Counter, defaultdict\n"
        f"upstream = ({upstream_host!r}, {int(upstream_port)!r})\n"
        f"timeout = {int(timeout)!r}\n"
        f"respect_schedule = {bool(respect_schedule)!r}\n"
        "manifest_path = os.environ['DYNET_RUNTIME_WORKLOAD_MANIFEST']\n"
        "out = os.environ['DYNET_RUNTIME_WORKLOAD_OUT']\n"
        "manifest = json.load(open(manifest_path))\n"
        "entries = [item for item in manifest.get('entries', []) if isinstance(item, dict)]\n"
        "routes = set()\n"
        "dns_cache = {}\n"
        "def run_json(command):\n"
        "    data = subprocess.run(command, check=True, capture_output=True, text=True).stdout\n"
        "    return json.loads(data or '[]')\n"
        "def elapsed_ms(start):\n"
        "    return int((time.monotonic() - start) * 1000)\n"
        "def unix_ms():\n"
        "    return int(time.time() * 1000)\n"
        "def classify(exc):\n"
        "    text = ('%s: %s' % (type(exc).__name__, exc)).lower()\n"
        "    if isinstance(exc, socket.gaierror) or 'name or service not known' in text:\n"
        "        return 'dns'\n"
        "    if isinstance(exc, TimeoutError) or 'timed out' in text or 'timeout' in text:\n"
        "        return 'timeout'\n"
        "    if isinstance(exc, ssl.SSLCertVerificationError) or 'certificate' in text:\n"
        "        return 'certificate'\n"
        "    if isinstance(exc, ssl.SSLError) or 'ssl' in text:\n"
        "        return 'tls'\n"
        "    if 'refused' in text:\n"
        "        return 'refused'\n"
        "    if 'reset' in text:\n"
        "        return 'reset'\n"
        "    if 'network is unreachable' in text:\n"
        "        return 'network-unreachable'\n"
        "    return 'other'\n"
        "def route_snapshot(ip):\n"
        "    try:\n"
        "        rows = run_json(['ip', '-j', 'route', 'get', ip])\n"
        "        row = rows[0] if rows else {}\n"
        "        dev = row.get('dev')\n"
        "        return {'routeObserved': True, 'routeDev': dev, 'routeViaDynet': dev == 'dynet0', 'routeSourcePresent': bool(row.get('prefsrc') or row.get('src'))}\n"
        "    except Exception as exc:\n"
        "        return {'routeObserved': False, 'routeErrorType': classify(exc)}\n"
        "def tun_link_stats():\n"
        "    try:\n"
        "        rows = run_json(['ip', '-j', '-s', 'link', 'show', 'dev', 'dynet0'])\n"
        "        row = rows[0] if rows else {}\n"
        "        stats = row.get('stats64') or row.get('stats') or {}\n"
        "        rx = stats.get('rx') or {}\n"
        "        tx = stats.get('tx') or {}\n"
        "        return {'observed': True, 'rxPackets': int(rx.get('packets') or 0), 'txPackets': int(tx.get('packets') or 0), 'rxBytes': int(rx.get('bytes') or 0), 'txBytes': int(tx.get('bytes') or 0)}\n"
        "    except Exception as exc:\n"
        "        return {'observed': False, 'errorType': classify(exc)}\n"
        "def tun_delta(before, after):\n"
        "    if not before.get('observed') or not after.get('observed'):\n"
        "        return {'observed': False}\n"
        "    return {'observed': True, 'rxPackets': after.get('rxPackets', 0) - before.get('rxPackets', 0), 'txPackets': after.get('txPackets', 0) - before.get('txPackets', 0), 'rxBytes': after.get('rxBytes', 0) - before.get('rxBytes', 0), 'txBytes': after.get('txBytes', 0) - before.get('txBytes', 0)}\n"
        "def read_name(data, offset):\n"
        "    labels = []\n"
        "    jumped = False\n"
        "    end = offset\n"
        "    seen = 0\n"
        "    while True:\n"
        "        if offset >= len(data):\n"
        "            raise ValueError('dns name exceeds packet')\n"
        "        length = data[offset]\n"
        "        if length & 0xc0 == 0xc0:\n"
        "            if offset + 1 >= len(data):\n"
        "                raise ValueError('dns pointer exceeds packet')\n"
        "            if not jumped:\n"
        "                end = offset + 2\n"
        "            offset = ((length & 0x3f) << 8) | data[offset + 1]\n"
        "            jumped = True\n"
        "            seen += 1\n"
        "            if seen > 16:\n"
        "                raise ValueError('dns pointer loop')\n"
        "            continue\n"
        "        offset += 1\n"
        "        if length == 0:\n"
        "            return '.'.join(labels), (end if jumped else offset)\n"
        "        labels.append(data[offset:offset + length].decode('ascii', 'ignore').lower())\n"
        "        offset += length\n"
        "def dns_query(name):\n"
        "    query_id = random.randrange(0, 65536)\n"
        "    packet = bytearray(query_id.to_bytes(2, 'big'))\n"
        "    packet.extend(b'\\x01\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00')\n"
        "    for label in name.split('.'):\n"
        "        encoded = label.encode('ascii')\n"
        "        packet.append(len(encoded))\n"
        "        packet.extend(encoded)\n"
        "    packet.extend(b'\\x00\\x00\\x01\\x00\\x01')\n"
        "    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)\n"
        "    sock.settimeout(timeout)\n"
        "    sock.sendto(bytes(packet), upstream)\n"
        "    data, _ = sock.recvfrom(4096)\n"
        "    if len(data) < 12 or data[:2] != query_id.to_bytes(2, 'big'):\n"
        "        raise ValueError('invalid dns response')\n"
        "    qd = int.from_bytes(data[4:6], 'big')\n"
        "    an = int.from_bytes(data[6:8], 'big')\n"
        "    offset = 12\n"
        "    for _ in range(qd):\n"
        "        _, offset = read_name(data, offset)\n"
        "        offset += 4\n"
        "    addresses = []\n"
        "    ttls = []\n"
        "    for _ in range(an):\n"
        "        _, offset = read_name(data, offset)\n"
        "        rtype = int.from_bytes(data[offset:offset+2], 'big')\n"
        "        ttl = int.from_bytes(data[offset+4:offset+8], 'big')\n"
        "        rdlen = int.from_bytes(data[offset+8:offset+10], 'big')\n"
        "        offset += 10\n"
        "        rdata = data[offset:offset+rdlen]\n"
        "        offset += rdlen\n"
        "        if rtype == 1 and rdlen == 4:\n"
        "            addresses.append('.'.join(str(b) for b in rdata))\n"
        "            ttls.append(ttl)\n"
        "    return {'_addresses': addresses, 'dnsAnswers': an, 'aRecords': len(addresses), 'minTtl': min(ttls) if ttls else None}\n"
        "def route_ip(ip):\n"
        "    before = route_snapshot(ip)\n"
        "    subprocess.run(['sudo', 'ip', 'route', 'replace', ip + '/32', 'dev', 'dynet0'], check=True)\n"
        "    routes.add(ip)\n"
        "    after = route_snapshot(ip)\n"
        "    return {'routeInstalled': True, 'routeBefore': before, 'routeAfter': after, 'routeViaDynet': after.get('routeViaDynet') is True, 'routeDev': after.get('routeDev')}\n"
        "def tcp_connect(ip):\n"
        "    sock = socket.create_connection((ip, 443), timeout=timeout)\n"
        "    sock.settimeout(timeout)\n"
        "    return {'_socket': sock, 'connectedFamily': 'ipv4', 'peerMatchesSelectedAddress': sock.getpeername()[0] == ip}\n"
        "def tls_wrap(name, sock):\n"
        "    context = ssl.create_default_context()\n"
        "    try:\n"
        "        tls = context.wrap_socket(sock, server_hostname=name)\n"
        "    except Exception:\n"
        "        sock.close()\n"
        "        raise\n"
        "    tls.settimeout(timeout)\n"
        "    return {'_tls': tls, 'tlsVersion': tls.version()}\n"
        "def close_connected_socket(sock):\n"
        "    try:\n"
        "        sock.shutdown(socket.SHUT_RDWR)\n"
        "    except Exception:\n"
        "        pass\n"
        "    sock.close()\n"
        "    return {'closedAfterConnect': True}\n"
        "def http_request(name, tls, method):\n"
        "    request = ('%s / HTTP/1.1\\r\\nHost: %s\\r\\nUser-Agent: dynet-private-runtime-workload/1\\r\\nAccept: */*\\r\\nConnection: close\\r\\nCache-Control: no-cache\\r\\n\\r\\n' % (method, name)).encode('ascii')\n"
        "    tls.sendall(request)\n"
        "    limit = 8192 if method == 'GET' else 4096\n"
        "    data = b''\n"
        "    while len(data) < limit:\n"
        "        chunk = tls.recv(min(4096, limit - len(data)))\n"
        "        if not chunk:\n"
        "            break\n"
        "        data += chunk\n"
        "        if method == 'HEAD' and b'\\r\\n\\r\\n' in data:\n"
        "            break\n"
        "    line = data.split(b'\\r\\n', 1)[0]\n"
        "    parts = line.split()\n"
        "    if len(parts) < 2 or not parts[1].isdigit():\n"
        "        raise ValueError('invalid HTTP status line')\n"
        "    status = int(parts[1])\n"
        "    return {'statusCode': status, 'statusClass': '%dxx' % (status // 100), 'responseBytesRead': len(data), 'responseBodyStored': False}\n"
        "def public(value):\n"
        "    if not isinstance(value, dict):\n"
        "        return {}\n"
        "    return {key: item for key, item in value.items() if not key.startswith('_')}\n"
        "def run_stage(result, name, func):\n"
        "    started = time.monotonic()\n"
        "    stage = {'name': name, 'ok': False}\n"
        "    try:\n"
        "        value = func()\n"
        "        stage.update(public(value))\n"
        "        stage['ok'] = True\n"
        "        return value\n"
        "    except Exception as exc:\n"
        "        stage['errorType'] = classify(exc)\n"
        "        stage['errorClass'] = type(exc).__name__\n"
        "        raise\n"
        "    finally:\n"
        "        stage['elapsedMs'] = elapsed_ms(started)\n"
        "        result.setdefault('stages', []).append(stage)\n"
        "def cached_dns(result, domain, force):\n"
        "    if not force and domain in dns_cache:\n"
        "        value = dns_cache[domain]\n"
        "        result.setdefault('stages', []).append({'name': 'dns-cache', 'ok': True, 'elapsedMs': 0, 'cacheHit': True, **public(value)})\n"
        "        return value\n"
        "    value = run_stage(result, 'dns', lambda domain=domain: dns_query(domain))\n"
        "    if value.get('_addresses'):\n"
        "        dns_cache[domain] = value\n"
        "    return value\n"
        "def percentile(values, target):\n"
        "    if not values:\n"
        "        return None\n"
        "    values = sorted(values)\n"
        "    return values[round((len(values) - 1) * (target / 100))]\n"
        "def aggregate(rows):\n"
        "    total = len(rows)\n"
        "    success = sum(1 for row in rows if row.get('ok'))\n"
        "    latencies = [int(row.get('elapsedMs') or 0) for row in rows]\n"
        "    return {'count': total, 'success': success, 'failure': total - success, 'successRate': round(success / total, 4) if total else 0, 'latencyMs': {'p50': percentile(latencies, 50), 'p95': percentile(latencies, 95), 'max': max(latencies) if latencies else None}}\n"
        "def grouped(rows, field):\n"
        "    groups = defaultdict(list)\n"
        "    for row in rows:\n"
        "        groups[str(row.get(field) or 'unknown')].append(row)\n"
        "    return [{'key': key, **aggregate(value)} for key, value in sorted(groups.items())]\n"
        "def stage_groups(rows):\n"
        "    groups = defaultdict(list)\n"
        "    for row in rows:\n"
        "        for stage in row.get('stages', []):\n"
        "            groups[str(stage.get('name'))].append(stage)\n"
        "    return [{'key': key, **aggregate(value)} for key, value in sorted(groups.items())]\n"
        "def top_errors(rows):\n"
        "    counter = Counter(str(row.get('errorType')) for row in rows if row.get('errorType'))\n"
        "    return [{'key': key, 'count': count} for key, count in counter.most_common(20)]\n"
        "started = time.monotonic()\n"
        "results = []\n"
        "try:\n"
        "    for entry in entries:\n"
        "        offset = int(entry.get('scheduledOffsetMs') or 0)\n"
        "        if respect_schedule:\n"
        "            due = started + offset / 1000\n"
        "            now = time.monotonic()\n"
        "            if due > now:\n"
        "                time.sleep(due - now)\n"
        "                lag = 0\n"
        "            else:\n"
        "                lag = int((now - due) * 1000)\n"
        "        else:\n"
        "            lag = None\n"
        "        item_start = time.monotonic()\n"
        "        item_started_at = unix_ms()\n"
        "        domain = str(entry.get('domain', '')).lower().strip('.')\n"
        "        probe = str(entry.get('probe') or 'https-head')\n"
        "        result = {'id': entry.get('id'), 'startedAtUnixMs': item_started_at, 'bucket': entry.get('bucket'), 'behavior': entry.get('behavior'), 'groupId': entry.get('groupId'), 'domain': domain, 'probe': probe, 'scheduledOffsetMs': entry.get('scheduledOffsetMs'), 'scheduleLagMs': lag, 'stages': []}\n"
        "        tun_before = tun_link_stats()\n"
        "        sock = None\n"
        "        tls = None\n"
        "        try:\n"
        "            dns = cached_dns(result, domain, probe == 'dns')\n"
        "            result.update(public(dns))\n"
        "            addresses = dns.get('_addresses', [])\n"
        "            if probe != 'dns':\n"
        "                if not addresses:\n"
        "                    raise RuntimeError('no A record')\n"
        "                ip = addresses[0]\n"
        "                result['selectedAddressIndex'] = 0\n"
        "                result['selectedAddressCount'] = len(addresses)\n"
        "                result['selectedAddressStored'] = False\n"
                "                result.update(public(run_stage(result, 'route', lambda ip=ip: route_ip(ip))))\n"
        "                tcp = run_stage(result, 'tcp-connect', lambda ip=ip: tcp_connect(ip))\n"
        "                sock = tcp.get('_socket')\n"
        "                result.update(public(tcp))\n"
        "                if probe == 'tcp-connect':\n"
        "                    result.update(public(run_stage(result, 'tcp-close', lambda sock=sock: close_connected_socket(sock))))\n"
        "                    sock = None\n"
        "                if probe in {'tls-handshake', 'https-head', 'https-get'}:\n"
        "                    tls_value = run_stage(result, 'tls-handshake', lambda domain=domain, sock=sock: tls_wrap(domain, sock))\n"
        "                    sock = None\n"
        "                    tls = tls_value.get('_tls')\n"
        "                    result.update(public(tls_value))\n"
        "                    if probe in {'https-head', 'https-get'}:\n"
        "                        method = 'GET' if probe == 'https-get' else 'HEAD'\n"
        "                        http = run_stage(result, 'http-' + method.lower(), lambda domain=domain, tls=tls, method=method: http_request(domain, tls, method))\n"
        "                        result.update(public(http))\n"
        "            result['ok'] = True\n"
        "        except Exception as exc:\n"
        "            result['ok'] = False\n"
        "            result['errorType'] = classify(exc)\n"
        "            result['errorClass'] = type(exc).__name__\n"
        "            result['error'] = str(exc)[:180]\n"
        "            failed = next((stage for stage in reversed(result.get('stages', [])) if not stage.get('ok')), None)\n"
        "            result['errorStage'] = failed.get('name') if failed else 'probe'\n"
        "        finally:\n"
        "            if tls is not None:\n"
        "                tls.close()\n"
        "            if sock is not None:\n"
        "                sock.close()\n"
        "            result['tunWitness'] = tun_delta(tun_before, tun_link_stats())\n"
        "            result['elapsedMs'] = elapsed_ms(item_start)\n"
        "            result['finishedAtUnixMs'] = unix_ms()\n"
        "            results.append(result)\n"
        "finally:\n"
        "    for ip in sorted(routes):\n"
        "        subprocess.run(['sudo', 'ip', 'route', 'del', ip + '/32', 'dev', 'dynet0'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n"
        "summary = {'schema': '" + WORKLOAD_PROBE_SCHEMA + "', 'manifestSchema': manifest.get('schema'), 'environment': manifest.get('environment'), 'seed': manifest.get('seed'), 'workload': manifest.get('workload', {}), 'privacy': {'identityInformationSent': False, 'cookiesSent': False, 'authorizationSent': False, 'responseBodiesStored': False, 'responseHeadersStored': False, 'resolvedIpAddressesStored': False}, 'totals': aggregate(results), 'byBucket': grouped(results, 'bucket'), 'byBehavior': grouped(results, 'behavior'), 'byProbe': grouped(results, 'probe'), 'byStage': stage_groups(results), 'errors': top_errors(results), 'durationActualMs': elapsed_ms(started), 'results': results}\n"
        "with open(out, 'w') as fh:\n"
        "    json.dump(summary, fh, sort_keys=True)\n"
        "print('[runtime-private] workload attempted=%d successRate=%s errors=%s' % (summary['totals']['count'], summary['totals']['successRate'], summary['errors']))\n"
        "PY_DYNET_PRIVATE_WORKLOAD\n"
    )
